name: comfyssh_flutter
description: A more comfortable SSH experience

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartssh2: ^2.8.2
  xterm: ^3.5.0
  virtual_keyboard_multi_language: ^1.0.3
  shared_preferences: ^2.1.0
  string_to_color: ^2.0.0
  flashy_tab_bar2: ^0.0.6
  animated_notch_bottom_bar: ^0.0.6
  virtual_keyboard_custom_layout: ^0.0.5
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  open_url: ^2.0.1
  flutter_web_browser: ^0.17.1
  introduction_screen: ^3.1.8
  in_app_review: ^2.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_rfb: ^0.6.2
  video_player: ^2.6.1
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  file: ^6.1.4
  sqflite: ^2.2.8+4
  flutter_speed_dial: ^7.0.0
  sqflite_common_ffi: ^2.2.5
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/play-store.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/play-store.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/play-store.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/play-store.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/distro/
    - database/


