name: comfyssh_flutter
description: A more comfortable Raspberry Pi experience

publish_to: 'none'

version: 2.0.0+9

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartssh2: ^2.8.2
  xterm: ^3.5.0
  virtual_keyboard_multi_language: ^1.0.3
  shared_preferences: ^2.1.0
  string_to_color: ^2.0.0
  flashy_tab_bar2: ^0.0.6
  animated_notch_bottom_bar: ^0.0.6
  virtual_keyboard_custom_layout: ^0.0.5
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  open_url: ^2.0.1
  flutter_web_browser: ^0.17.1
  introduction_screen: ^3.1.8
  in_app_review: ^2.0.6
  flutter_launcher_icons: ^0.11.0
  flutter_rfb: ^0.6.2
  video_player: ^2.6.1
  camera: ^0.10.5+7
  path_provider: ^2.0.15
  file: ^6.1.4
  sqflite: ^2.2.8+4
  flutter_speed_dial: ^7.0.0
  sqflite_common_ffi: ^2.2.5
  flutter_staggered_grid_view: ^0.7.0
  animated_toggle_switch: ^0.7.0
  flutter_switch: ^0.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  google_nav_bar: ^5.0.6
  webview_flutter: ^4.2.4
  flutter_inappwebview: ^6.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_markdown: ^0.6.15
  provider: ^6.0.5
  loader_overlay: ^2.3.2
  overlay_support: ^2.1.0
  flutter_overlay_loader: ^2.0.0
  flutter_draggable_gridview: ^0.0.8
  network_tools: any
  network_info_plus: ^4.1.0
  lan_scanner: ^4.0.0+1
  dart_ping_ios: ^4.0.2
  screen_recorder: ^0.2.0
  knob_widget: ^1.0.3
  speech_to_text: ^6.5.1
  icons_launcher: ^2.0.7
  webview_universal: ^0.0.5
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.2.0
  gal: ^2.3.0
  web_socket_channel: ^2.4.0
  file_saver: any
  flutter_mjpeg: ^2.0.4
  chewie: ^1.7.5
  awesome_snackbar_content: ^0.1.3
  top_snackbar_flutter: ^3.1.0
  dio: ^5.4.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  gap: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  innosetup: ^0.1.3
  msix: ^3.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/comfySpaceIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/comfySpaceIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/comfySpaceIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/comfySpaceIcon.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/distro/
    - assets/comfyWeb/
    - database/
    - assets/comfySpaceIcon.png
    - assets/speedDialIcons/
    - assets/secretshit/WireDashSecret.txt
    - assets/secretshit/WireDashProjectID.txt


msix_config:
  display_name: ComfySpace
  publisher_display_name: Thomas Nguyen
  publishing_folder_path: build/msix
  identity_name: tech.comfystudio.comfyspace
  msix_version: 1.0.0.0
  logo_path: assets/comfySpaceIcon.png
  capabilities: internetClient, microphone


icons_launcher:
  image_path: "assets/comfySpaceIcon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/comfySpaceIcon.png"
    ios:
      enable: true
      image_path: "assets/comfyspace_icon_ios.png"
    web:
      enable: true
      image_path: "assets/comfySpaceIcon.png"
      favicon_path: "assets/comfySpaceIcon.png"
    macos:
      enable: true
      image_path: "assets/comfySpaceIcon.png"
    windows:
      enable: true
      image_path: "assets/comfySpaceIcon.png"
    linux:
      enable: true
      image_path: "assets/comfySpaceIcon.png"